### ISSUE TITLE
issues with index.html

### ISSUE THREAD

**Issue by bailey-collins** [Media-Ed-Online/intro-web-dev-resources#4]
When I try to update my index html page (saving in Atom, refreshing in the browser) it doesn't change anything and loses all my progress. The only success I had was extracting the files and trying again to change the title, which worked, but then I ran into the same problem again a few moments later when I tried to complete the next part of the assignment. I haven't been able to attach any images, and none of my readme files have displayed or saved correctly. I've tried reorganizing my files, but nothing I've done has worked so far. I can attach screenshots if that helps.

**Comment by JustineEvansUM** [comment]
Hey, @bailey-collins 

Your repo and live site look great! I can see both text and code. This is your live site: https://bailey-collins.github.io/web-dev-hw./project-1/

As for your readme files, I think your problem is the lack of extension. All readme files should have the `.md` extension. For example, **readme.md**

You can change this at any time by right-clicking on a file, selected Rename, and adding `.md` to the end.

That should fix many of your markdown problems. Start there, and ping me again!
