### ISSUE TITLE
Backwards loading

### ISSUE THREAD

**Issue by ashtonmwilson** [Media-Ed-Online/intro-web-dev-resources#8]
If I build a specific repo in git hub, is it possible to later upload sub files directly into to that repo through atom/git hub desktop? It seems like it is wanting me to create a new repo each time. And or, after downloading a github repo to my finder, how do I have it reconnect with itself in GitHub?

**Comment by ashtonmwilson** [comment]
https://www.git-tower.com/learn/git/commands/git-clone
nvm

**Comment by ashtonmwilson** [comment]
Well actually cloning, only answered half of my question.

**Comment by jballas** [comment]
@ashtonmwilson I don't know how helpful I can be, since I'm using windows.

But you connect your repo online to your repo on your computer with Github desktop. 

I think you just have to double check which is your 'Current Repository' in Github desktop.
![image](https://user-images.githubusercontent.com/42751526/55268383-ce163780-524e-11e9-84a1-718be1c1ba4a.png)

Then you can push files or pull them from that specific repo. Does that make sense?

**Comment by JustineEvansUM** [comment]
Hey, @ashtonmwilson;
I'm looking at your [web-dev-hw](https://github.com/ashtonmwilson/web-dev-hw) repo, and it looks like your tracking changes just fine. Is this still an issue?
